/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AgentWorkInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptJob"
      | "agents"
      | "entryFee"
      | "jobs"
      | "joinPlatform"
      | "nextJobId"
      | "owner"
      | "platformFeeBps"
      | "postJob"
      | "releasePayment"
      | "setSecurityStatus"
      | "updateProfile"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "JobCreated"
      | "JobPaid"
      | "JobTaken"
      | "MemberJoined"
      | "ProfileUpdated"
      | "SecurityVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "entryFee", values?: undefined): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "joinPlatform",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "nextJobId", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "postJob", values: [string]): string;
  encodeFunctionData(
    functionFragment: "releasePayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSecurityStatus",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProfile",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "acceptJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "entryFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "joinPlatform",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextJobId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "postJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releasePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSecurityStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    employer: AddressLike,
    budget: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, employer: string, budget: bigint];
  export interface OutputObject {
    jobId: bigint;
    employer: string;
    budget: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobPaidEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    worker: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [jobId: bigint, worker: string, amount: bigint];
  export interface OutputObject {
    jobId: bigint;
    worker: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobTakenEvent {
  export type InputTuple = [jobId: BigNumberish, worker: AddressLike];
  export type OutputTuple = [jobId: bigint, worker: string];
  export interface OutputObject {
    jobId: bigint;
    worker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberJoinedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileUpdatedEvent {
  export type InputTuple = [agent: AddressLike, metadata: string];
  export type OutputTuple = [agent: string, metadata: string];
  export interface OutputObject {
    agent: string;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecurityVerifiedEvent {
  export type InputTuple = [agent: AddressLike, isSafe: boolean];
  export type OutputTuple = [agent: string, isSafe: boolean];
  export interface OutputObject {
    agent: string;
    isSafe: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentWork extends BaseContract {
  connect(runner?: ContractRunner | null): AgentWork;
  waitForDeployment(): Promise<this>;

  interface: AgentWorkInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptJob: TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, string, bigint, bigint, bigint] & {
        isMember: boolean;
        isVerifiedSafe: boolean;
        metadata: string;
        reputation: bigint;
        jobsCompleted: bigint;
        totalEarned: bigint;
      }
    ],
    "view"
  >;

  entryFee: TypedContractMethod<[], [bigint], "view">;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, boolean, boolean, bigint] & {
        id: bigint;
        employer: string;
        worker: string;
        budget: bigint;
        description: string;
        isCompleted: boolean;
        isPaid: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  joinPlatform: TypedContractMethod<[_metadata: string], [void], "payable">;

  nextJobId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  postJob: TypedContractMethod<[_description: string], [void], "payable">;

  releasePayment: TypedContractMethod<
    [_jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSecurityStatus: TypedContractMethod<
    [_agent: AddressLike, _isSafe: boolean],
    [void],
    "nonpayable"
  >;

  updateProfile: TypedContractMethod<[_metadata: string], [void], "nonpayable">;

  withdrawFees: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptJob"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, string, bigint, bigint, bigint] & {
        isMember: boolean;
        isVerifiedSafe: boolean;
        metadata: string;
        reputation: bigint;
        jobsCompleted: bigint;
        totalEarned: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "entryFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, boolean, boolean, bigint] & {
        id: bigint;
        employer: string;
        worker: string;
        budget: bigint;
        description: string;
        isCompleted: boolean;
        isPaid: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinPlatform"
  ): TypedContractMethod<[_metadata: string], [void], "payable">;
  getFunction(
    nameOrSignature: "nextJobId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "postJob"
  ): TypedContractMethod<[_description: string], [void], "payable">;
  getFunction(
    nameOrSignature: "releasePayment"
  ): TypedContractMethod<[_jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSecurityStatus"
  ): TypedContractMethod<
    [_agent: AddressLike, _isSafe: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateProfile"
  ): TypedContractMethod<[_metadata: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "JobPaid"
  ): TypedContractEvent<
    JobPaidEvent.InputTuple,
    JobPaidEvent.OutputTuple,
    JobPaidEvent.OutputObject
  >;
  getEvent(
    key: "JobTaken"
  ): TypedContractEvent<
    JobTakenEvent.InputTuple,
    JobTakenEvent.OutputTuple,
    JobTakenEvent.OutputObject
  >;
  getEvent(
    key: "MemberJoined"
  ): TypedContractEvent<
    MemberJoinedEvent.InputTuple,
    MemberJoinedEvent.OutputTuple,
    MemberJoinedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileUpdated"
  ): TypedContractEvent<
    ProfileUpdatedEvent.InputTuple,
    ProfileUpdatedEvent.OutputTuple,
    ProfileUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SecurityVerified"
  ): TypedContractEvent<
    SecurityVerifiedEvent.InputTuple,
    SecurityVerifiedEvent.OutputTuple,
    SecurityVerifiedEvent.OutputObject
  >;

  filters: {
    "JobCreated(uint256,address,uint256)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "JobPaid(uint256,address,uint256)": TypedContractEvent<
      JobPaidEvent.InputTuple,
      JobPaidEvent.OutputTuple,
      JobPaidEvent.OutputObject
    >;
    JobPaid: TypedContractEvent<
      JobPaidEvent.InputTuple,
      JobPaidEvent.OutputTuple,
      JobPaidEvent.OutputObject
    >;

    "JobTaken(uint256,address)": TypedContractEvent<
      JobTakenEvent.InputTuple,
      JobTakenEvent.OutputTuple,
      JobTakenEvent.OutputObject
    >;
    JobTaken: TypedContractEvent<
      JobTakenEvent.InputTuple,
      JobTakenEvent.OutputTuple,
      JobTakenEvent.OutputObject
    >;

    "MemberJoined(address)": TypedContractEvent<
      MemberJoinedEvent.InputTuple,
      MemberJoinedEvent.OutputTuple,
      MemberJoinedEvent.OutputObject
    >;
    MemberJoined: TypedContractEvent<
      MemberJoinedEvent.InputTuple,
      MemberJoinedEvent.OutputTuple,
      MemberJoinedEvent.OutputObject
    >;

    "ProfileUpdated(address,string)": TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
    ProfileUpdated: TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;

    "SecurityVerified(address,bool)": TypedContractEvent<
      SecurityVerifiedEvent.InputTuple,
      SecurityVerifiedEvent.OutputTuple,
      SecurityVerifiedEvent.OutputObject
    >;
    SecurityVerified: TypedContractEvent<
      SecurityVerifiedEvent.InputTuple,
      SecurityVerifiedEvent.OutputTuple,
      SecurityVerifiedEvent.OutputObject
    >;
  };
}
